# Generated by Django 5.0.3 on 2024-04-08 23:27

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
