# Generated by Django 5.0.3 on 2024-04-09 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_currency_code_alter_currency_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currency'},
        ),
    ]
