# Generated by Django 5.0.3 on 2024-04-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_size_options_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
