# Generated by Django 5.0.3 on 2024-04-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_blog_aforism_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('pinterest', models.URLField()),
                ('twitter', models.URLField()),
                ('youtube', models.URLField()),
                ('logo', models.ImageField(upload_to='logo/')),
                ('blog_bg_image', models.ImageField(upload_to='blog_bg/')),
                ('location', models.URLField(max_length=2000)),
                ('slogan', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Setting',
            },
        ),
    ]
