# Generated by Django 5.0.3 on 2024-04-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='aforism',
            field=models.CharField(max_length=500),
        ),
    ]
