# Generated by Django 5.0.3 on 2024-04-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='aforism_az',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='aforism_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='aforism_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='desription_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='desription_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='desription_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug_az',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug_en',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug_ru',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
