# Generated by Django 5.0.3 on 2024-05-02 17:56

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_shopimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'ShopComments',
                'verbose_name_plural': 'ShopComments',
            },
        ),
    ]
