# Generated by Django 5.0.3 on 2024-05-05 21:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
