# Generated by Django 5.0.3 on 2024-05-05 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
