# Generated by Django 5.0.3 on 2024-05-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
