# Generated by Django 5.0.3 on 2024-05-13 18:53

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_product_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopcomments',
            options={'ordering': ('-created_at',), 'verbose_name': 'Shop Comment', 'verbose_name_plural': 'Shop Comments'},
        ),
        migrations.RemoveField(
            model_name='shopcomments',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shopcomments',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='shopcomments',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shopcomments', to='core.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopcomments',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopcomments',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region=None),
        ),
    ]
