# Generated by Django 5.0.3 on 2024-05-13 19:05

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_shopcomments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcomments',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None),
        ),
    ]
