# Generated by Django 5.0.3 on 2024-05-13 20:57

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_blogcomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomments',
            options={'ordering': ('-created_at',), 'verbose_name': 'Blog Comment', 'verbose_name_plural': 'Blog Comments'},
        ),
        migrations.RenameField(
            model_name='blogcomments',
            old_name='text',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='blogcomments',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcomments',
            name='name',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcomments',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=20, region=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogcomments',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogcomments', to='core.blog'),
        ),
    ]
