# Generated by Django 5.0.3 on 2024-04-13 21:09

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_myuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
